#[allow(non_snake_case)]
[package]
name = "rustPiano"
version = "0.1.0"
edition = "2021"

[dependencies]
midir = "0.10.1"
rustysynth = "1.3.3"
cpal = "0.15.3"
winit = "0.28"
image = "0.25.5"
pixels = "0.13"